name: Deploy to server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs 
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }} 
          port: ${{ secrets.PORT }} 
          script: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'echo SSH command executed successfully'
            cd /Odoo/env/env15/addons/pipeline_test
            git pull origin master # we pull any changes from git
            sudo systemctl stop odoo.service
            sudo systemctl start odoo.service
