name: Deploy to server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs 
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }} 
          script: |
            cd /Odoo/env/env15/addons/new_pipeline_test
            git pull origin master # we pull any changes from git
      - name: service stop and upgrade module       
        run: sudo apt-get update
